#!/bin/bash

set -e

shopt -s expand_aliases

alias uaac='BUNDLE_GEMFILE=/home/tempest-web/tempest/web/vendor/uaac/Gemfile bundle exec uaac'

# TODO: grab these from .opsmanrc ?
OPSMAN_USER=admin
CLIENT_ID=opsman
CLIENT_SECRET=

cmd=$1

usage_and_exit() {
  cat <<EOF >&2
Usage: opsman <command> [options]
Examples:
  opsman login
  opsman upload cf-1.8.5-build.4.pivotal
EOF
}

error_and_exit() {
  echo $1 >&2
  exit 1
}

is_valid_access_token() {
  local accessToken=$1

  [ -n "$accessToken" ] || return 1

  local statusCode=$(curl http://localhost/uaa/check_token -k -L -G \
    -s -o /dev/null -w "%{http_code}" \
    -u "$CLIENT_ID:$CLIENT_SECRET" \
    -d token_type=bearer \
    -d token="$accessToken")

    [ "200" = "$statusCode" ]
}

upload_to_opsman() {
  if [ -z "$1" ]; then
    read -r -p "Local file name: " LOCAL_FILE_NAME
  else
    LOCAL_FILE_NAME=$1
  fi

  if [ ! -f "$LOCAL_FILE_NAME" ]; then
    error_and_exit "Invalid file: $LOCAL_FILE_NAME"
  fi

  UAA_ACCESS_TOKEN=$(uaac context $OPSMAN_USER | grep access_token | awk '{ print $2 }')

  if [ ! is_valid_access_token ]; then
    uaac-login
    UAA_ACCESS_TOKEN=$(uaac context $OPSMAN_USER | grep access_token | awk '{ print $2 }')
  fi

  curl "https://localhost/api/v0/available_products" \
    -k -# -o /dev/null \
    -X POST \
    -H "Authorization: Bearer $UAA_ACCESS_TOKEN" \
    -F "product[file]=@$LOCAL_FILE_NAME"
}

if [ "login" = "$cmd" ]; then
  uaac-login
elif [ "upload" = "$cmd" ]; then
  upload_to_opsman $2
else
  usage_and_exit
fi
