#!/bin/bash

set -e

shopt -s expand_aliases

alias uaac='BUNDLE_GEMFILE=/home/tempest-web/tempest/web/vendor/uaac/Gemfile bundle exec uaac'

# TODO: grab these from .opsmanrc ?
OPSMAN_USER=admin
CLIENT_ID=opsman
CLIENT_SECRET=

cmd=$1

error_and_exit() {
  echo $1 >&2
  exit 1
}

is_valid_access_token() {
  local accessToken=$1

  [ -n "$accessToken" ] || return 1

  local statusCode=$(curl http://localhost/uaa/check_token -k -L -G \
    -s -o /dev/null -w "%{http_code}" \
    -u "$CLIENT_ID:$CLIENT_SECRET" \
    -d token_type=bearer \
    -d token="$accessToken")

    [ "200" = "$statusCode" ]
}

if [ "upload" = "$cmd" ]; then
  pivnet-upload $2
elif [ "download" = "$cmd" ]; then
  pivnet-download $2
elif [ "login" = "$cmd" ]; then
  uaac-login
else
  print_usage
fi
