#!/bin/bash

set -e

shopt -s expand_aliases

cmd=$1

usage_and_exit() {
  cat <<EOF >&2
Usage: opsman <command> [options]
Examples:
  pivnet login
  pivnet download https://network.pivotal.io/.../product_files/7509/download
EOF
}

error_and_exit() {
  echo $1 >&2
  exit 1
}

if [ "login" = "$cmd" ]; then
  error_and_exit "login not implemented yet"
elif [ "download" = "$cmd" ]; then
  pivnet-download $2
else
  usage_and_exit
fi
