#!/bin/bash
#
# Pivotal Network Product Tile Upload-to-Ops-Manager Script
#
# This script is intended to be run from the Ops Manager VM to upload a local .pivotal
# product file.  This script needs a UAA access token for authentication.
#
# To install the client run (this is probably already installed):
# $ gem install cf-uaac
#
# Use the client to target UAA and generate a token:
# $ uaac target https://localhost/uaa --skip-ssl-validation
# $ uaac token owner get
#   Client name: opsman
#   Client secret: <empty>
#   User name: <opsMgrUserName>
#   Password: <opsMgrPassword>
#
# Export UAA access token variable:
# $ export UAA_ACCESS_TOKEN=$(uaac context <opsMgrUserName> | grep access_token | awk '{ print $2 }')
#
# If UAAC isn't available use the following KB to try CURL:
# *Use at your own risk!*
# https://discuss.pivotal.io/hc/en-us/articles/219118768
#
# Usage:
# $ ./pivnet-upload.sh <p-some-tile-1.0.0.pivotal>
#

set -e

shopt -s expand_aliases

alias uaac='BUNDLE_GEMFILE=/home/tempest-web/tempest/web/vendor/uaac/Gemfile bundle exec uaac'

# TODO: grab these from .pivnetrc ?
OPSMAN_USER=admin
CLIENT_ID=opsman
CLIENT_SECRET=

error_and_exit() {
  echo $1 >&2
  exit 1
}

is_valid_access_token() {
  local accessToken=$1

  [ -n "$accessToken" ] || return 1

  local statusCode=$(curl http://localhost/uaa/check_token -k -L -G \
    -s -o /dev/null -w "%{http_code}" \
    -u "$CLIENT_ID:$CLIENT_SECRET" \
    -d token_type=bearer \
    -d token="$accessToken")

    [ "200" = "$statusCode" ]
}

# Prompt for the file if the user didn't specify it
if [ -z "$1" ]; then
  read -r -p "Local file name: " LOCAL_FILE_NAME
else
  LOCAL_FILE_NAME=$1
fi

if [ ! -f "$LOCAL_FILE_NAME" ]; then
  error_and_exit "Invalid file: $LOCAL_FILE_NAME"
fi

# Login to UAA if we don't have a valid token
UAA_ACCESS_TOKEN=$(uaac context $OPSMAN_USER | grep access_token | awk '{ print $2 }')

[ ! $(which uaac-loginx) ] && echo "Cannot find 'uaac-login'. Please install it from opsman-scripts!"

[ ! is_valid_access_token ] && uaac-login

curl "https://localhost/api/v0/available_products" \
  -k -# -o /dev/null \
  -X POST \
  -H "Authorization: Bearer $UAA_ACCESS_TOKEN" \
  -F "product[file]=@$LOCAL_FILE_NAME"
