#!/bin/bash

shopt -s expand_aliases

alias uaac='BUNDLE_GEMFILE=/home/tempest-web/tempest/web/vendor/uaac/Gemfile bundle exec uaac'

if [ -z "$OPSMAN_USER" ]; then
  read -p "Ops Manager User: " OPSMAN_USER
fi

if [ -z "$OPSMAN_PASS" ]; then
  read -rs -p "Ops Manager Pass: " OPSMAN_PASS
fi

uaac target https://localhost/uaa --ca-cert /var/tempest/workspaces/default/root_ca_certificate

uaac token owner get opsman $OPSMAN_USER -p $OPSMAN_PASS -s ''

export UAA_ACCESS_TOKEN=$(uaac context $OPSMAN_USER | grep access_token | awk '{ print $2 }')
